baseURL: 'https://www.bernardo.me'
languageCode: 'en-us'
title: 'Bernardo Farah'
theme: 'bernardo.me'
params:
  author: "Bernardo Farah"
  googleid: "G-47ZTPHD1CM"
  email: "hi@bernardo.me"
  location: "Seattle WA, USA"
  homepage: "www.bernardo.me"
  tagline: Engineering Leader & Dad
  socials:
    - icon: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/berfarah
    - icon: github
      name: Github
      url: https://github.com/berfarah

markup:
  highlight:
    noClasses: false

sitemap:
  changefreq: monthly
  priority: 0.5

taxonomies:
